version: '3.5'
services:
  api1: # API - Instância 01
    image: rinha
    container_name: api1
    hostname: api1
    depends_on:
      - db
    ports:
      - "8081:80"
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.8GB'
    networks:
      - api_network
    environment:
      PORT: 8081

  api2: # API - Instância 02
    image: rinha
    container_name: api2
    hostname: api2
    depends_on:
      - db
    ports:
      - "8082:80"
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.8GB'
    networks:
      - api_network
    environment:
      PORT: 8082

  nginx: # Load Balancer
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'
    networks:
      - api_network

  db: # Banco de dados
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.2GB'
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: ggrun
      POSTGRES_PASSWORD: 123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api_network
networks:
  api_network:
    driver: bridge